apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-web-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  # Uncomment and set to match your cluster. Omitted, the default StorageClass is used.
  # storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
